Repository CrazyPingu/OOP21-MAP, pull requests merged in 2022-06, with the labels that each got.

#187 Show enemy range
  .gitignore
  src/controller/game_controller/BasicGameController.java
  src/utilities/ImageModifier.java
  src/utilities/RoomConstant.java
  src/view/MenuButton.java
  src/view/game/central/GameArea.java
  src/view/game/central/GameButton.java
Labels: optional

#188 Fix teleportation bug
  src/view/game/central/GameButton.java
Labels: hotfix

#193 Fix test
  src/model/room/works/RandomArtefactList.java
  src/test/AroundAreaTest.java
  src/test/CrossAreaTest.java
  src/test/ExtendibleMaxLifeSystemTest.java
  src/test/GameObjectSpawnTest.java
  src/test/HealLifeSystemTest.java
  src/test/PlayerTest.java
  src/test/PosInGridTest.java
  src/test/RoomTest.java
  src/test/SimpleEntityTest.java
  src/test/SimpleLifeSystemTest.java
  src/view/loading_screen/LoadingScreenImpl.java
Labels: hotfix

#197 Update readme
  README.md
Labels: optional

#198 Card layout enum
  src/controller/CardName.java
  src/controller/GameLoop.java
  src/controller/PageController.java
  src/view/frame/BasicFrame.java
Labels: hotfix

#199 Enemy AI hotfix
  src/controller/enemy_ai/EnemyAIImpl.java
  src/controller/game_controller/BasicGameController.java
  src/test/EnemyAITest.java
Labels: hotfix

#200 Player reachablecells hotfix
  src/controller/enemy_ai/EnemyAIImpl.java
  src/model/game_object/MovingObject.java
  src/model/game_object/entity/Player.java
  src/model/game_object/entity/SimpleEnemy.java
  src/view/game/central/GameArea.java
Labels: refactor

#203 Obstacle feature
  src/controller/GameAreaController.java
  src/controller/enemy_ai/EnemyAIImpl.java
  src/controller/game_controller/GameController.java
  src/model/game_object/obstacle/Obstacle.java
  src/model/game_object/obstacle/ObstacleFactory.java
  src/model/game_object/obstacle/ObstacleFactoryImpl.java
  src/model/room/Room.java
  src/model/room/RoomImpl.java
  src/model/room/works/RandomArtefactList.java
  src/model/room/works/RandomEnemyList.java
  src/model/room/works/RandomObstacleList.java
  src/resources/obstacle/Rock.png
  src/resources/obstacle/pebble.png
  src/utilities/RoomConstant.java
  src/utilities/texture/EntityTexture.java
  src/view/MenuButton.java
  src/view/MenuLabel.java
  src/view/game/central/GameArea.java
Labels: mandatory

#206 Entity refactor
  src/model/game_object/ArtefactUserObject.java
  src/model/game_object/MovingObject.java
  src/model/game_object/MultipleActionObject.java
  src/model/game_object/entity/Entity.java
  src/model/game_object/entity/Player.java
  src/model/game_object/entity/SimpleEnemy.java
Labels: refactor

#205 Add obstacles test
  src/test/EnemyAITest.java
Labels: hotfix

#207 Enum in weapon & enemy factory
  src/controller/game_controller/BasicGameController.java
  src/model/game_object/entity/enemy/EnemyFactory.java
  src/model/game_object/entity/enemy/EnemyFactoryImpl.java
  src/model/strategy/weapon/WeaponFactory.java
  src/model/strategy/weapon/WeaponFactoryImpl.java
Labels: refactor

#209 changed game object interface structure
  src/model/game_object/ArtefactUserObject.java
  src/model/game_object/GameObject.java
  src/model/game_object/KillableObject.java
  src/model/game_object/MovingObject.java
  src/model/game_object/WeaponizedObject.java
  src/model/game_object/entity/Entity.java
Labels: refactor

#210 General hoftfix
  src/model/game_object/artefact/MovementArtefactFactoryImp.java
  src/model/game_object/entity/Entity.java
  src/model/game_object/entity/SimpleEnemy.java
  src/model/life/impl/ExtendibleMaxLifeSystem.java
  src/model/life/impl/HealLifeSystem.java
  src/model/life/impl/SimpleLifeSystem.java
  src/model/life_system/ExtendibleMaxHealthSystem.java
  src/model/life_system/HealSystem.java
  src/model/life_system/LifeSystem.java
  src/test/AroundAreaTest.java
  src/test/CrossAreaTest.java
  src/test/SimpleEntityTest.java
Labels: hotfix

#211 Action menu javadoc
  src/view/game/action/ActionMenu.java
  src/view/game/action/action_button/AttackAction.java
  src/view/game/action/action_button/MoveAction.java
  src/view/game/action/action_button/PauseAction.java
  src/view/game/action/action_button/SkipAction.java
Labels: documentation

#212 Add javadoc to obstacle
  src/model/game_object/obstacle/Obstacle.java
  src/model/game_object/obstacle/ObstacleFactory.java
  src/model/game_object/obstacle/ObstacleFactoryImpl.java
Labels: documentation

#214 Javadoc
  src/controller/ActionMenuController.java
  src/controller/PageController.java
  src/model/room/works/RandomObstacleList.java
  src/view/MenuButton.java
  src/view/MenuLabel.java
  src/view/end_game_menu/Defeat.java
  src/view/end_game_menu/EndGameMenu.java
  src/view/end_game_menu/Victory.java
  src/view/game/action/ActionMenu.java
  src/view/game/action/action_button/AttackAction.java
  src/view/game/action/action_button/MoveAction.java
  src/view/game/action/action_button/PauseAction.java
  src/view/game/action/action_button/SkipAction.java
  src/view/pause/PauseMenu.java
  src/view/pause/action/MainMenuAction.java
  src/view/pause/action/QuitAction.java
  src/view/pause/action/ResumeAction.java
Labels: documentation

#215 Controller game area documentation
  src/controller/CardName.java
  src/controller/GameAreaController.java
  src/controller/RandomRoomGenerator.java
  src/model/room/RoomFactoryImpl.java
Labels: documentation

#216 add javadoc to utilities
  src/utilities/ImageModifier.java
  src/utilities/Pair.java
  src/utilities/RoomConstant.java
Labels: documentation

#217 add javadoc to view
  src/view/BasicFrame.java
  src/view/game/TotalPanel.java
Labels: documentation

#218 Add javadoc
  src/controller/enemy_ai/EnemyAIImpl.java
  src/view/game/log_stats/Log.java
  src/view/game/log_stats/ScrollPaneAppearance.java
  src/view/game/log_stats/ScrollableLog.java
  src/view/game/log_stats/ScrollableStats.java
  src/view/game/log_stats/Stats.java
  src/view/game/log_stats/TextAreaAppearance.java
Labels: documentation

#221 Add javadoc
  src/controller/enemy_ai/EnemyAIImpl.java
  src/controller/game_controller/BasicGameController.java
  src/model/game_object/entity/enemy/EnemyFactory.java
  src/model/game_statistics/GameStatisticsImpl.java
  src/model/weapon/WeaponFactory.java
  src/model/weapon/WeaponFactoryImpl.java
  src/test/AsteriskAreaTest.java
  src/test/EnemyAITest.java
  src/view/game/log_stats/ScrollPaneAppearance.java
  src/view/game/log_stats/ScrollableLog.java
  src/view/game/log_stats/ScrollableStats.java
Labels: documentation

#220 add javadoc
  src/controller/GameLoop.java
  src/controller/PageController.java
Labels: documentation

#223 General hotfix
  src/model/game_object/artefact/factories/ActionNumberArtefactFactory.java
  src/model/game_object/artefact/factories/ActionNumberArtefactFactoryImpl.java
  src/model/game_object/artefact/factories/HealthArtefactFactory.java
  src/model/game_object/artefact/factories/HealthArtefactFactoryImpl.java
  src/model/game_object/artefact/factories/MovementArtefactFactory.java
  src/model/game_object/artefact/factories/MovementArtefactFactoryImp.java
  src/model/game_object/artefact/factories/WeaponArtefactFactory.java
  src/model/game_object/artefact/factories/WeaponArtefactFactoryImpl.java
  src/model/room/works/RandomArtefactList.java
  src/test/AsteriskAreaTest.java
  src/test/CrossAreaTest.java
  src/test/EnemyAITest.java
  src/test/ExtendibleMaxLifeSystemTest.java
  src/test/HealLifeSystemTest.java
  src/test/PlayerTest.java
  src/test/PosInGridTest.java
  src/test/RoomTest.java
  src/test/SimpleEntityTest.java
  src/test/SimpleLifeSystemTest.java
Labels: documentation, hotfix

#225 End Game screen refactor
  src/resources/endGame/Defeat.png
  src/resources/endGame/Victory.png
  src/utilities/texture/EntityTexture.java
Labels: refactor

#226 Update uml
  .gitignore
  img/uml/Artefact.png
  img/uml/Enemy.png
  img/uml/EnemyAI.png
  img/uml/GameArea.png
  img/uml/GameArea2.png
  img/uml/LifeSystem.png
  img/uml/Movement.png
  img/uml/Room.png
  img/uml/Room2.png
  img/uml/StatsLog.png
  img/uml/Weapon.png
  img/uml/loading_screen.png
  plantuml/EnemyAI.plantuml
  plantuml/EnemyWeapon.plantuml
  plantuml/GameArea.plantuml
  plantuml/LoadingScreen.plantuml
  plantuml/Room.plantuml
  plantuml/StatisticsLog.plantuml
  plantuml/artefact.plantuml
  plantuml/lifeSystem.plantuml
  plantuml/movement.plantuml
  report.pdf
  report.tex
Labels: documentation
