Repository CrazyPingu/OOP21-MAP, pull requests merged in 2022-05, with the labels that each got.

#46 Player feature
  src/logics/game_object/ArtefactUserObject.java
  src/logics/game_object/entity/Player.java
  src/logics/game_object/entity/SimpleEntity.java
  src/logics/life/ExtendibleMaxLifeSystem.java
  src/logics/life/HealLifeSystem.java
  src/test/PlayerTest.java
Labels: mandatory

#49 correct ax into axe
  src/logics/strategy/weapon/WeaponFactoryImpl.java
Labels: mandatory

#47 Artefact implementation
  src/logics/game_object/artefact/Artefact.java
  src/logics/game_object/artefact/ArtefactFactory.java
  src/logics/game_object/artefact/HealthArtefactFactory.java
  src/logics/game_object/artefact/HealthArtefactFactoryImpl.java
  src/logics/game_object/artefact/MovementArtefactFactory.java
  src/logics/game_object/artefact/MovementArtefactFactoryImp.java
  src/logics/game_object/artefact/WeaponArtefactFactory.java
  src/logics/game_object/artefact/WeaponArtefactFactoryImpl.java
  src/resources/artefact/health/placeholder
  src/resources/artefact/movement/placeholder
  src/resources/artefact/weapon/placeholder
  src/resources/weapon/placeholder
  src/utilis/texture/ArtefactTexture.java
Labels: mandatory

#52 Action Number hotfix
  src/logics/game_object/ArtefactUserObject.java
  src/logics/game_object/MultipleActionObject.java
  src/logics/game_object/WeaponizedObject.java
  src/logics/game_object/artefact/ActionNumberArtefactFactory.java
  src/logics/game_object/artefact/ActionNumberArtefactFactoryImpl.java
  src/logics/game_object/entity/Player.java
  src/logics/game_object/entity/SimpleEntity.java
  src/utilis/texture/ArtefactTexture.java
Labels: mandatory

#50 Stats and log feature
  src/view/game/log/placeholder
  src/view/game/logStats/Log.java
  src/view/game/logStats/ScrollPaneAppearance.java
  src/view/game/logStats/ScrollableLog.java
  src/view/game/logStats/ScrollableStats.java
  src/view/game/logStats/Stats.java
  src/view/game/logStats/TextAreaAppearance.java
  src/view/game/stats/placeholder
Labels: mandatory

#53 changed method name from getNumberAction to getActionNumber
  src/logics/game_object/MultipleActionObject.java
  src/logics/game_object/entity/Player.java
Labels: Hotfix

#54 fix player import
  src/view/game/logStats/ScrollableStats.java
  src/view/game/logStats/Stats.java
Labels: Hotfix

#56 Room hotfix
  src/logics/room/type/BigRoom.java
  src/logics/room/type/RandomRoom.java
  src/logics/room/type/SmallRoom.java
  src/logics/room/works/RandomArtefactList.java
  src/logics/room/works/RandomEnemyList.java
  src/logics/room/works/RandomEnemyMap.java
  src/logics/room/works/Room.java
  src/logics/room/works/RoomFactoryImpl.java
  src/logics/room/works/RoomImpl.java
  src/utilis/Constant.java
  src/utilis/RoomConstant.java
  src/view/game/central/GameButton.java
Labels: mandatory

#57 rename class SimpleEntity into SimpleEnemy and update references
  src/logics/game_object/entity/SimpleEnemy.java
  src/logics/game_object/entity/enemy/EnemyFactory.java
  src/logics/game_object/entity/enemy/EnemyFactoryImpl.java
  src/logics/room/works/RandomArtefactList.java
  src/logics/room/works/RandomEnemyList.java
  src/logics/room/works/Room.java
  src/logics/room/works/RoomImpl.java
  src/test/SimpleEntityTest.java
  src/utilis/RoomConstant.java
Labels: wontfix

#58 Rename package from utilis to utilities
  src/logics/game_object/GameObject.java
  src/logics/game_object/MovingObject.java
  src/logics/game_object/artefact/ActionNumberArtefactFactory.java
  src/logics/game_object/artefact/ActionNumberArtefactFactoryImpl.java
  src/logics/game_object/artefact/Artefact.java
  src/logics/game_object/artefact/HealthArtefactFactory.java
  src/logics/game_object/artefact/HealthArtefactFactoryImpl.java
  src/logics/game_object/artefact/MovementArtefactFactory.java
  src/logics/game_object/artefact/MovementArtefactFactoryImp.java
  src/logics/game_object/artefact/WeaponArtefactFactory.java
  src/logics/game_object/artefact/WeaponArtefactFactoryImpl.java
  src/logics/game_object/entity/Player.java
  src/logics/game_object/entity/SimpleEnemy.java
  src/logics/game_object/entity/enemy/EnemyFactory.java
  src/logics/game_object/entity/enemy/EnemyFactoryImpl.java
  src/logics/room/type/BigRoom.java
  src/logics/room/type/RandomRoom.java
  src/logics/room/type/SmallRoom.java
  src/logics/room/works/RandomArtefactList.java
  src/logics/room/works/RandomEnemyList.java
  src/logics/room/works/Room.java
  src/logics/room/works/RoomFactoryImpl.java
  src/logics/room/works/RoomImpl.java
  src/logics/strategy/Strategy.java
  src/logics/strategy/concrete_strategies/AroundArea.java
  src/logics/strategy/concrete_strategies/AsteriskArea.java
  src/logics/strategy/concrete_strategies/CrossArea.java
  src/logics/strategy/movement/Movement.java
  src/logics/strategy/movement/MovementImpl.java
  src/logics/strategy/weapon/Weapon.java
  src/logics/strategy/weapon/WeaponImpl.java
  src/test/AroundAreaTest.java
  src/test/AsteriskAreaTest.java
  src/test/CrossAreaTest.java
  src/test/PlayerTest.java
  src/test/PosInGridTest.java
  src/test/SimpleEntityTest.java
  src/utilis/texture/ArtefactTexture.java
  src/utilis/texture/EntityTexture.java
  src/utilities/Constant.java
  src/utilities/GbcDimension.java
  src/utilities/ImageMethod.java
  src/utilities/ImageModifier.java
  src/utilities/Pair.java
  src/utilities/PosInGrid.java
  src/utilities/RoomConstant.java
  src/view/game/TotalPanel.java
  src/view/game/central/GameArea.java
  src/view/game/central/GameButton.java
  src/view/game/logStats/ScrollPaneAppearance.java
  src/view/game/logStats/TextAreaAppearance.java
  src/view/loadingScreen/LoadingScreenImpl.java
  src/view/pause/PauseMenu.java
Labels: enhancement

#60 add texture
  src/resources/artefact/health/Big_Heal.png
  src/resources/artefact/health/Health_Extender.png
  src/resources/artefact/health/Little_Heal.png
  src/resources/artefact/health/placeholder
  src/resources/artefact/movement/Action_Number_Increaser.png
  src/resources/artefact/movement/Run.png
  src/resources/artefact/movement/Step.png
  src/resources/artefact/movement/placeholder
  src/resources/artefact/weapon/Axe.png
  src/resources/artefact/weapon/Dagger.png
  src/resources/artefact/weapon/Gun.png
  src/resources/artefact/weapon/Stick.png
  src/resources/artefact/weapon/Tube.png
  src/resources/artefact/weapon/placeholder
  src/resources/enemy/ZombieAxe.png
  src/resources/enemy/ZombieDagger.png
  src/resources/enemy/ZombieGun.png
  src/resources/enemy/ZombieStick.png
  src/resources/enemy/ZombieTube.png
  src/resources/enemy/placeholder
  src/resources/player/player.png
Labels: mandatory

#62 Action menu feature
  src/controller/ActionFlag.java
  src/controller/ActionMenuController.java
  src/controller/GameAreaController.java
  src/controller/PageController.java
  src/controller/RandomRoomGenerator.java
  src/controller/gameController/GameController.java
  src/logics/game_object/artefact/ActionNumberArtefactFactoryImpl.java
  src/logics/game_object/artefact/HealthArtefactFactoryImpl.java
  src/logics/game_object/artefact/MovementArtefactFactoryImp.java
  src/logics/game_object/artefact/WeaponArtefactFactoryImpl.java
  src/logics/game_object/entity/enemy/EnemyFactoryImpl.java
  src/logics/room/works/RandomArtefactList.java
  src/logics/room/works/RandomEnemyList.java
  src/logics/room/works/Room.java
  src/logics/room/works/RoomFactoryImpl.java
  src/logics/room/works/RoomImpl.java
  src/resources/room/door.png
  src/utilities/Constant.java
  src/utilities/ImageModifier.java
  src/utilities/Pair.java
  src/utilities/RoomConstant.java
  src/utilities/texture/ArtefactTexture.java
  src/utilities/texture/EntityTexture.java
  src/view/MenuButton.java
  src/view/frame/BasicFrame.java
  src/view/game/TotalPanel.java
  src/view/game/action/ActionMenu.java
  src/view/game/action/ButtonsAction/AttackAction.java
  src/view/game/action/ButtonsAction/MoveAction.java
  src/view/game/action/ButtonsAction/PauseAction.java
  src/view/game/action/ButtonsAction/SkipAction.java
  src/view/game/action/placeholder
  src/view/game/central/GameArea.java
  src/view/game/central/GameButton.java
  src/view/loadingScreen/LoadingScreenImpl.java
Labels: mandatory

#63 Stats log hotfix
  src/view/game/logStats/ScrollableLog.java
  src/view/game/logStats/ScrollableStats.java
Labels: Hotfix

#65 Player hotfix
  src/logics/game_object/entity/Player.java
  src/test/PlayerTest.java
Labels: Hotfix

#66 Action menu feature hotfix
  src/view/MenuButton.java
  src/view/game/action/ActionMenu.java
  src/view/game/action/ButtonsAction/AttackAction.java
Labels: Hotfix

#67 Game area feature
  src/view/game/TotalPanel.java
  src/view/game/central/GameArea.java
Labels: mandatory

#68 Pause menu hotfix
  src/controller/PageController.java
  src/view/pause/PauseMenu.java
  src/view/pause/action/MainMenuAction.java
  src/view/pause/action/QuitAction.java
  src/view/pause/action/ResumeAction.java
Labels: Hotfix

#69 Fix totalpanel
  src/view/game/TotalPanel.java
Labels: Hotfix

#64 Basic game controller feature
  src/controller/enemyAI/EnemyAI.java
  src/controller/enemyAI/EnemyAIImpl.java
  src/controller/gameController/BasicGameController.java
  src/test/EnemyAITest.java
Labels: mandatory

#71 Enemy AI hotfix
  src/controller/enemyAI/EnemyAIImpl.java
  src/test/EnemyAITest.java
  src/view/game/TotalPanel.java
Labels: Hotfix

#72 Controller
  src/controller/ActionMenuController.java
  src/controller/GameAreaController.java
  src/controller/GameLoop.java
  src/controller/PageController.java
  src/controller/gameController/GameController.java
Labels: mandatory

#73 Game controller hotfix
  src/controller/GameLoop.java
  src/controller/Main.java
  src/controller/gameController/GameController.java
Labels: Hotfix

#74 add parameters to constructor
  src/controller/gameController/BasicGameController.java
Labels: Hotfix

#76 Total panel hotfix
  src/view/game/TotalPanel.java
  src/view/game/central/GameArea.java
  src/view/game/central/GameButton.java
Labels: mandatory

#77 change action number method's call
  src/controller/gameController/BasicGameController.java
Labels: Hotfix

#75 Add getter and setter of currentActionNumber
  src/controller/gameController/GameController.java
Labels: Hotfix

#78 change method's name
  src/controller/gameController/GameController.java
Labels: Hotfix

#79 change method's name
  src/controller/gameController/BasicGameController.java
Labels: Hotfix

#80 Main menu
  src/controller/GameLoop.java
  src/controller/PageController.java
  src/view/mainMenu/MainMenu.java
  src/view/mainMenu/NewGameAction.java
  src/view/mainMenu/placeholder
Labels: mandatory

#82 End game menu feature
  src/resources/endGame/Defeat.png
  src/resources/endGame/Victory.png
  src/resources/player/empty_hearth.png
  src/resources/player/full_hearth.png
  src/resources/player/half_hearth.png
  src/view/endGameMenu/EndGameMenu.java
Labels: mandatory

#84 Fix Action Menu Buttons methods
  src/view/game/action/ButtonsAction/AttackAction.java
  src/view/game/action/ButtonsAction/MoveAction.java
Labels: Hotfix

#85 Add parameters
  src/test/EnemyAITest.java
Labels: Hotfix

#86 Action menu hotfix
  src/controller/gameController/GameController.java
  src/view/game/action/ActionMenu.java
  src/view/game/action/ButtonsAction/AttackAction.java
  src/view/game/action/ButtonsAction/MoveAction.java
Labels: Hotfix

#87 Player hotfix
  src/logics/game_object/entity/Player.java
  src/test/PlayerTest.java
Labels: Hotfix

#88 Game controller hotfix
  src/controller/gameController/GameController.java
Labels: mandatory

#89 remove parameter from player constructor
  src/test/EnemyAITest.java
Labels: Hotfix

#90 Fix GameLoop
  src/controller/GameLoop.java
  src/controller/PageController.java
  src/view/endGameMenu/EndGameMenu.java
Labels: Hotfix

#91 End menu hotfix
  src/controller/GameLoop.java
  src/view/endGameMenu/Defeat.java
  src/view/endGameMenu/EndGameMenu.java
  src/view/endGameMenu/Victory.java
Labels: mandatory

#93 Game statistics feature
  src/logics/game_statistics/GameStatistics.java
  src/logics/game_statistics/GameStatisticsImpl.java
  src/utilities/counter/Counter.java
  src/utilities/counter/CounterImpl.java
Labels: mandatory

#94 Controller hotfix
  src/controller/GameAreaController.java
  src/controller/GameLoop.java
  src/controller/gameController/BasicGameController.java
  src/controller/gameController/GameController.java
Labels: bug, mandatory

#95 Basic game controller refactor
  src/controller/gameController/BasicGameController.java
Labels: mandatory

#96 change parameters
  src/controller/gameController/BasicGameController.java
Labels: Hotfix

#97 Fix GameController and GameLoop
  src/controller/GameLoop.java
  src/controller/gameController/GameController.java
Labels: Hotfix

#98 Add toString to stats display
  src/controller/gameController/GameController.java
  src/logics/game_statistics/GameStatistics.java
  src/logics/game_statistics/GameStatisticsImpl.java
  src/view/game/logStats/Stats.java
Labels: Hotfix

#100 Translate Log output to english
  src/controller/gameController/GameController.java
Labels: Hotfix

#101 Game area hotfix
  src/utilities/RoomConstant.java
  src/view/game/central/GameArea.java
  src/view/game/central/GameButton.java
Labels: Hotfix

#102 correct parameter gameStats
  src/controller/gameController/BasicGameController.java
  src/view/game/logStats/ScrollableStats.java
  src/view/game/logStats/Stats.java
Labels: Hotfix

#103 correct getter name
  src/controller/gameController/BasicGameController.java
Labels: Hotfix

#104 Update from GameStatistics to GameStatisticsImpl in GameController
  src/controller/gameController/GameController.java
Labels: Hotfix

#106 Fix totalpanel import
  src/view/game/TotalPanel.java
Labels: Hotfix

#105 Fix GameLoop
  src/controller/GameLoop.java
Labels: Hotfix

#107 Fix RandomRoomGenerator
  src/controller/RandomRoomGenerator.java
Labels: Hotfix

#108 Fix Creation of GameStatisticsImpl
  src/controller/GameLoop.java
Labels: Hotfix

#109 Log stats hotfix
  src/controller/gameController/BasicGameController.java
  src/logics/game_statistics/GameStatistics.java
  src/logics/game_statistics/GameStatisticsImpl.java
Labels: Hotfix

#110 Fix Buttons in ActionMenu
  src/view/game/action/ActionMenu.java
  src/view/game/action/ButtonsAction/AttackAction.java
  src/view/game/action/ButtonsAction/MoveAction.java
Labels: Hotfix

#111 Fix Buttons in PauseMenu
  src/view/pause/PauseMenu.java
Labels: Hotfix

#112 Fix gbcDimension scaling
  src/utilities/GbcDimension.java
Labels: Hotfix

#114 Fix loading screen aspect ratio
  src/view/loadingScreen/LoadingScreenImpl.java
Labels: Hotfix

#116 Modify the update of stats
  src/controller/gameController/GameController.java
Labels: Hotfix

#118 Graphics fix
  src/view/game/central/GameArea.java
  src/view/loadingScreen/LoadingScreenImpl.java
Labels: enhancement

#120 Fix Buttons dimension
  src/view/endGameMenu/EndGameMenu.java
Labels: Hotfix

#121 fixed call of the player constructor
  src/test/PlayerTest.java
Labels: Hotfix

#122 add attack and move action counter
  src/logics/game_statistics/GameStatistics.java
  src/logics/game_statistics/GameStatisticsImpl.java
Labels: Hotfix

#123 add current action in stats display
  src/controller/gameController/BasicGameController.java
  src/controller/gameController/GameController.java
  src/logics/game_statistics/GameStatisticsImpl.java
  src/view/game/TotalPanel.java
  src/view/game/logStats/ScrollableStats.java
  src/view/game/logStats/Stats.java
Labels: Hotfix

#125 Fixed current action number display
  src/controller/gameController/GameController.java
  src/view/game/logStats/Stats.java
Labels: Hotfix

#126 Add game stats to total panel constructor
  src/test/EnemyAITest.java
Labels: Hotfix

#129 Game object spawn test
  src/test/GameObjectSpawnTest.java
Labels: Optional

#128 Room test
  src/test/RoomTest.java
Labels: Optional

#127 Fix button sprite
  src/resources/artefact/placeholder
  src/resources/room/BlueBall.png
  src/resources/room/RedBall.png
  src/resources/room/door.png
  src/utilities/RoomConstant.java
  src/view/game/central/GameArea.java
  src/view/game/central/GameButton.java
Labels: enhancement

#130 Plugin installation
  .checkstyle
  .eclipse-pmd
  .project
  .settings/edu.umd.cs.findbugs.core.prefs
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/pmd/pmd.xml
Labels: enhancement

#133 Rename packages
  src/controller/GameLoop.java
  src/controller/enemy_ai/EnemyAI.java
  src/controller/enemy_ai/EnemyAIImpl.java
  src/controller/game_controller/BasicGameController.java
  src/controller/game_controller/GameController.java
  src/test/EnemyAITest.java
Labels: Hotfix

#134 Add final to fields
  src/controller/enemy_ai/EnemyAI.java
  src/controller/enemy_ai/EnemyAIImpl.java
Labels: Hotfix

#135 Add final to fields
  src/controller/game_controller/BasicGameController.java
Labels: Hotfix

#136 Remove public in interface and add final to fields
  src/logics/game_statistics/GameStatistics.java
  src/logics/game_statistics/GameStatisticsImpl.java
  src/utilities/counter/Counter.java
Labels: Hotfix

#137 Room hotfix
  src/logics/room/type/BigRoom.java
  src/logics/room/type/RandomRoom.java
  src/logics/room/type/SmallRoom.java
  src/logics/room/works/RandomArtefactList.java
  src/logics/room/works/RandomEnemyList.java
  src/logics/room/works/Room.java
  src/logics/room/works/RoomFactory.java
  src/logics/room/works/RoomFactoryImpl.java
  src/logics/room/works/RoomImpl.java
Labels: Hotfix

#138 Log stats hotfix
  src/view/game/logStats/Log.java
  src/view/game/logStats/ScrollPaneAppearance.java
  src/view/game/logStats/ScrollableLog.java
  src/view/game/logStats/ScrollableStats.java
  src/view/game/logStats/Stats.java
  src/view/game/logStats/TextAreaAppearance.java
Labels: Hotfix

#139 Loading screen hotfix
  src/utilities/RoomConstant.java
  src/view/loadingScreen/LoadingScreen.java
  src/view/loadingScreen/LoadingScreenImpl.java
Labels: Hotfix

#140 Game object hotfix
  src/logics/game_object/ArtefactUserObject.java
  src/logics/game_object/GameObject.java
  src/logics/game_object/KillableObject.java
  src/logics/game_object/MovingObject.java
  src/logics/game_object/MultipleActionObject.java
  src/logics/game_object/WeaponizedObject.java
  src/logics/game_object/artefact/ActionNumberArtefactFactory.java
  src/logics/game_object/artefact/ActionNumberArtefactFactoryImpl.java
  src/logics/game_object/artefact/Artefact.java
  src/logics/game_object/artefact/HealthArtefactFactory.java
  src/logics/game_object/artefact/HealthArtefactFactoryImpl.java
  src/logics/game_object/artefact/MovementArtefactFactory.java
  src/logics/game_object/artefact/MovementArtefactFactoryImp.java
  src/logics/game_object/artefact/WeaponArtefactFactory.java
  src/logics/game_object/artefact/WeaponArtefactFactoryImpl.java
  src/logics/game_object/entity/Player.java
  src/logics/game_object/entity/SimpleEnemy.java
  src/logics/game_object/entity/enemy/EnemyFactory.java
  src/logics/game_object/entity/enemy/EnemyFactoryImpl.java
Labels: Hotfix

#141 remove public and add final to fields
  src/logics/strategy/weapon/Weapon.java
  src/logics/strategy/weapon/WeaponFactory.java
  src/logics/strategy/weapon/WeaponFactoryImpl.java
  src/logics/strategy/weapon/WeaponImpl.java
Labels: Hotfix

#142 Constant hotfix
  .settings/org.eclipse.jdt.core.prefs
  src/utilities/Constant.java
  src/utilities/GbcDimension.java
  src/utilities/ImageMethod.java
  src/utilities/ImageModifier.java
  src/utilities/Pair.java
  src/utilities/PosInGrid.java
Labels: Hotfix

#143 Fix frame
  src/view/frame/BasicFrame.java
Labels: Hotfix

#144 Fix PauseMenu plugin error
  src/view/pause/PauseMenu.java
  src/view/pause/action/MainMenuAction.java
  src/view/pause/action/QuitAction.java
  src/view/pause/action/ResumeAction.java
Labels: Hotfix

#145 Fix MenuButton plugin error
  src/view/MenuButton.java
Labels: Hotfix

#146 Total panel fix
  src/view/game/TotalPanel.java
  src/view/game/central/GameArea.java
  src/view/game/central/GameButton.java
Labels: Hotfix

#147 Fix ActionMenu plugin error
  src/view/game/action/ActionMenu.java
  src/view/game/action/ButtonsAction/AttackAction.java
  src/view/game/action/ButtonsAction/MoveAction.java
  src/view/game/action/ButtonsAction/PauseAction.java
  src/view/game/action/ButtonsAction/SkipAction.java
Labels: Hotfix

#150 Room test hotfix
  src/test/GameObjectSpawnTest.java
  src/test/RoomTest.java
Labels: Hotfix

#149 Fix endGameMenu plugin error
  src/view/endGameMenu/Defeat.java
  src/view/endGameMenu/EndGameMenu.java
  src/view/endGameMenu/Victory.java
Labels: Hotfix

#151 Fix Controller plugin error
  src/controller/ActionFlag.java
  src/controller/ActionMenuController.java
  src/controller/GameAreaController.java
  src/controller/GameLoop.java
  src/controller/Main.java
  src/controller/PageController.java
  src/controller/game_controller/GameController.java
Labels: Hotfix

#152 Fix rnadomRoomGenerator
  src/controller/RandomRoomGenerator.java
Labels: Hotfix

#153 Movement hotfix
  src/logics/strategy/movement/Movement.java
  src/logics/strategy/movement/MovementFactory.java
  src/logics/strategy/movement/MovementFactoryImpl.java
  src/logics/strategy/movement/MovementImpl.java
Labels: Hotfix

#155 Strategy hotfix
  src/logics/strategy/Strategy.java
  src/logics/strategy/concrete_strategies/AroundArea.java
  src/logics/strategy/concrete_strategies/AsteriskArea.java
  src/logics/strategy/concrete_strategies/CrossArea.java
  src/logics/strategy/concrete_strategies/VariableDistanceConstants.java
Labels: Hotfix

#160 Life system refactor
  src/logics/life/ExtendibleMaxHealthSystem.java
  src/logics/life/HealSystem.java
  src/logics/life/LifeSystem.java
  src/logics/life/impl/ExtendibleMaxLifeSystem.java
  src/logics/life/impl/HealLifeSystem.java
Labels: refactor

#161 Remove pause background image and add MenuLabel class
  src/resources/pause/Background.jpg
  src/view/MenuLabel.java
  src/view/pause/PauseMenu.java
Labels: Hotfix

#162 Main menu label refactor
  src/view/main_menu/MainMenu.java
Labels: refactor

#163 Action menu hotfix
  src/view/game/action/ActionMenu.java
Labels: Hotfix

#164 Remove useless import
  src/view/game/action/ActionMenu.java
Labels: Hotfix

#166 Medium room
  src/logics/room/RoomFactory.java
  src/logics/room/RoomFactoryImpl.java
  src/logics/room/type/MediumRoom.java
  src/test/GameObjectSpawnTest.java
  src/test/RoomTest.java
  src/utilities/RoomConstant.java
Labels: enhancement

#167 Remove spottbugs
  src/controller/PageController.java
  src/controller/RandomRoomGenerator.java
  src/logics/room/works/RandomArtefactList.java
  src/logics/room/works/RandomEnemyList.java
  src/utilities/Constant.java
  src/utilities/ImageMethod.java
  src/utilities/ImageModifier.java
  src/utilities/Pair.java
  src/utilities/PosInGrid.java
  src/utilities/RoomConstant.java
  src/view/game/central/GameArea.java
  src/view/loading_screen/LoadingScreenImpl.java
Labels: enhancement

#168 Total panel hotfix
  src/view/game/TotalPanel.java
Labels: Hotfix

#172 Fix Action Number after skip
  src/controller/game_controller/GameController.java
Labels: Hotfix

#176 Remove room from game area
  src/controller/GameAreaController.java
  src/controller/GameLoop.java
  src/controller/Main.java
  src/controller/enemy_ai/EnemyAIImpl.java
  src/controller/game_controller/BasicGameController.java
  src/controller/game_controller/GameController.java
  src/view/game/TotalPanel.java
  src/view/game/central/GameArea.java
Labels: Hotfix

#177 delete useless import from heal life system
  src/model/life/impl/HealLifeSystem.java
  src/resources/player/Player.png
Labels: Hotfix

#184 Test init change
  src/test/EnemyAITest.java
Labels: Hotfix

#185 Enemy AI refactor
  src/controller/enemy_ai/EnemyAIImpl.java
  src/controller/game_controller/BasicGameController.java
Labels: refactor
